//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using SimpleBrowser;
        ///&lt;!doctype html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;@Model.Title&lt;/title&gt;
        ///		&lt;style type=&quot;text/css&quot;&gt;
        ///		&lt;/style&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		@foreach(HttpRequestLog log in Model.Logs) {
        ///		&lt;div class=&quot;log&quot;&gt;
        ///			&lt;ul&gt;
        ///				&lt;li&gt;&lt;b class=&quot;label&quot;&gt;URL:&lt;/b&gt; &lt;span class=&quot;value&quot;&gt;@log.Url&lt;/span&gt;&lt;/li&gt;
        ///				&lt;li&gt;&lt;b class=&quot;label&quot;&gt;Method:&lt;/b&gt; &lt;span class=&quot;value&quot;&gt;@log.Method&lt;/span&gt;&lt;/li&gt;
        ///				&lt;li&gt;&lt;b class=&quot;label&quot;&gt;Status Code:&lt;/b&gt; &lt;span class=&quot;value&quot;&gt;@log.StatusCode&lt;/span&gt;&lt;/li&gt;
        ///			&lt;/ul&gt;
        ///		&lt;/div&gt;
        ///		}
        ///	&lt;/body&gt;
        ///&lt;/ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlLogTemplate {
            get {
                return ResourceManager.GetString("HtmlLogTemplate", resourceCulture);
            }
        }
    }
}
